//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensiEdge.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class ConectedDevice : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConectedDevice defaultInstance = ((ConectedDevice)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConectedDevice())));
        
        public static ConectedDevice Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong BluetoothAddress {
            get {
                return ((ulong)(this["BluetoothAddress"]));
            }
            set {
                this["BluetoothAddress"] = value;
            }
        }
    }
}
